import { api, HydrateClient } from "~/trpc/server";
import { SignInComponent } from "./_components/SignInComponent";
import Image from "next/image";
import { useUser } from "@clerk/nextjs";

export default async function Home() {
  const posts = await api.post.getLatest();

  return (
    <>
      <HydrateClient>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        {/* <SignInComponent /> */}
        <div className="flex min-h-screen flex-col p-4 text-white">
          <div className="mb-4 flex flex-col items-center">
            <Image
              src="/profileImage.jpg"
              alt="Profile Image"
              width={60}
              height={60}
              className="mb-2 rounded-full"
            />
            <input
              placeholder="Type an emoji"
              className="rounded-lg border border-gray-300 bg-transparent p-2 text-gray-700"
            />
          </div>

          <div className="flex flex-col items-center">
            {posts.map((post) => (
              <div
                key={post.id}
                className="m-2 flex w-full max-w-2xl flex-col items-center justify-center rounded-lg bg-rose-200 p-4 shadow-lg"
              >
                <div className="text-lg font-semibold">{post.content}</div>
                <div className="text-sm text-gray-600">
                  Posted at: {new Date(post.createdAt).toLocaleString()}
                </div>
              </div>
            ))}
          </div>
        </div>
      </HydrateClient>
    </>
  );
}
