import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

import { api, HydrateClient } from "~/trpc/server";

export default async function Home() {
  const hello = await api.post.hello({ text: "from tRPC" });

  return (
    <>
      <HydrateClient>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
          <SignIn routing="hash" />
        </main>
      </HydrateClient>
    </>
  );
}
